# Generated by Django 4.2.17 on 2026-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Рецепт'),
        ),
    ]
